### ISSUE TITLE
There are no instructions for using standard CA-issued certificates

### ISSUE THREAD

**Issue by lewellyn** [loomio/loomio-deploy#1]
I was noticing that there are a few shortcomings in the documentation. One of the most glaring being that the only SSL configuration instructions are for using Let's Encrypt.

While Let's Encrypt is a fine service and I applaud what they're trying to accomplish, I view their service as supplementary to the established CA-issued certificate method. Especially when one is trying to deploy behind a firewall where there may be a local CA, Let's Encrypt isn't the best choice.

I assume that the certificate needs to go in `/root/loomio-deploy/certificates` with a well-known name. Does the intermediate chain need to be included? Does the key need to be in the same file?

It would be nice if the README had a couple of lines for "advanced installs" of SSL certificates to point those of us with existing certificates to use them. :)

**Comment by robguthrie** [comment]
@lewellyn thanks for the feedback, it's super helpful.

Certificates should be full chain, and can actually be put anywhere. The important thing is to specify their path correctly in the ENV file.

So I often copy CA issued certificates into certificates and update the LOOMIO_SSL_KEY and LOOMIO_SSL_CERT variables in the ENV file to match.

**Comment by robguthrie** [comment]
I've got an update to the readme on it's way. Please let me know what else you think I need to add to this.

**Comment by robguthrie** [comment]
Would this have explained it well enough?

> If you have a CA issued certificate or want to generate your own certificate, that's supported too. Just copy your full chain certificate file and the private key file into the `certificates` directory and update the values of `LOOMIO_SSL_KEY` and `LOOMIO_SSL_CERT` in your `env` file.

**Comment by lewellyn** [comment]
Yes, that would have saved a lot of trying and failing to figure it out. I figured it had to be easier than what I was thinking. Hopefully that addition to the README will help others in the future! :)

(Though, sadly, I can’t actually use Loomio without LDAP authentication, but that’s not exactly relevant to this issue.)

**Comment by robguthrie** [comment]
Interesting to hear @lewellyn. Do you work for an organisation with a budget that might pay for such an integration?
