### ISSUE TITLE
No feedback in UI for too big attachments

### ISSUE THREAD

**Issue by modulistic** [loomio/loomio-deploy#10]
When trying to upload a not so small attachment in a thread, the upload attempt ends silently with no hint of the failure, or with a few attempts at uploading.

Some kind of error message would be great.

I would also suggest adding a variable to the ```env``` file, e.g. ```MAX_ATTACHMENT_SIZE_ALLOWED```.

On the server logs you can see:

    [error] 32#32: *291 client intended to send too large body: 1921632 bytes, [...] , request: "POST /api/v1/attachments HTTP/1.1" [...]

**Comment by juliencarnot** [comment]
It seems to me [this commit](https://github.com/loomio/loomio-deploy/commit/183e8835842f1c119bd740bee8e6fdbb01e2b4ce#diff-26d8e0e204c82bca4f881dff7255a41a) is related, but does it fix the issue?

**Comment by robguthrie** [comment]
Yea, so Loomio itself does not have a max file size for attachements.
 
nginx in the loomio-deploy repo has a max file size, which was too small (like 2mb) - so I recently upped to 200mb. If your deploy is from a while ago you'll need to git pull the updates.

Caution that I found I had some filesystem permissions getting in my way when I updated a few older sites, so you may need to chmod and rm the nginx conf.d directory. Sorry I can't be more specific.
