### ISSUE TITLE
No mail delivery

### ISSUE THREAD

**Issue by raphaelpoitevin-ed** [loomio/loomio-deploy#100]
Hello,

I'd like to test Loomio in a local network. I installed stable version from docker. I don't manage to deliver mails. We have our own SMTP at 192.168.x.x on port 25 and no SSL/TLS. which works as well. But when I try to subscribe from form registration, it doesn't send any email. The code is well asked. I don't see any call to our SMTP in logs. no error nor warning. No trace in SMTP logs.

Thanks for help.

Regards,

Raphaël

**Comment by robguthrie** [comment]
I'm sure it will work with the right settings.

You'll need to share your SMTP config from the Loomio .env file.

Also run `docker compose logs -f` , and send through only the logs from when you click "Sign in with email" (not everything, just the log activity when you click this button)

Then we will have something to work with :)

**Comment by raphaelpoitevin-ed** [comment]
Hello,
Thanks for your answer.

Here is the .env:

```
LOOMIO_CONTAINER_IMAGE=loomio/loomio
LOOMIO_CONTAINER_TAG=v2.21.2
MAILIN_CONTAINER_IMAGE=loomio/mailin-docker
MAILIN_CONTAINER_TAG=latest
POSTGRES_CONTAINER_TAG=15.3

# this is the hostname of your app eg: loomio.org
CANONICAL_HOST=localhost

# email address of admin of the server for LetsEncrypt
SUPPORT_EMAIL=myemail@mydomain.tld

# the human name of the app (Default Loomio)
SITE_NAME=localhost

# reply-to in email notifications
REPLY_HOSTNAME=localhost

# hostname of the node.js app that handles websocket stuff
CHANNELS_URI=wss://channels.localhost

# smtp settings
SMTP_AUTH=plain
SMTP_DOMAIN=mydomain.tld
SMTP_SERVER=192.168.15.99
SMTP_PORT=25
SMTP_USERNAME=xxx
SMTP_PASSWORD=xxx
SMTP_SSL_VERIFY_MODE=none
#SMTP_USE_SSL=1
```

I tested with several loomio versions.

If I send a test mail inside the container for instance with swaks, it works.

For the moment, I just want to test in a local area, with internal domain. I don't need any https with letsencrypt etc. But basically there is no relation with.

I read logs after clicking on "create account" but I don't see any call to the SMTP. In development mode, I can see the email is forged as well.

Regards,

Raphaël

**Comment by robguthrie** [comment]
It might be worthwhile sharing the logs, because I still don't know whats wrong and can't help yet.

**Comment by raphaelpoitevin-ed** [comment]
Dear Robert,
      
Sorry for the delay, I was in holidays.
      
Here is logs: https://paste.vtech.fr/?fda2c96d61d6a260#9BB4hTwee2vPtCCNLp7SGVeT8cQGHLHRps1ZmcMJTgSd
      
For test I init in development mode, but it is the same in production mode.
      
Regards,
      
Raphaël

**Comment by robguthrie** [comment]
Sorry, I can't help with this. Closing the issue, as it's not a Loomio problem, it's just rails.
