### ISSUE TITLE
Cannot use LetsEncrypt

### ISSUE THREAD

**Issue by kawigreen14r** [loomio/loomio-deploy#102]
**Problem**:  Our AWS account forces us to explicitly enter CIDR ranges for ANY incoming requests in nacls and security groups.  This kills the ability to use LetEncrypt as it requires a separate verification sent by them, and they don't list IP ranges.  So I followed a post (https://github.com/loomio/loomio-deploy/issues/49) to remove nginx and letsencrypt, but now I can't seem to hit the server.  

I have Route53 records setup as per your instructions, and can use nslookup to see if gets through that fine.  I also removed that FORCE-SSL command, but nothing.

Questions:

1. Since that post I used was from 2019, is there anything I should add/remove to do the same?
2. could you suggest another alternative for our CIDR range limitations?
3. I'm a Rails newb, are there simple commands I can use in the Rails console to see traffic?
4. Will accessing the url require the usage of ports or any other redirects?
5. Can I use nginx without letsencrypt, and if so, where is the nginx routing config?

Attached the logs showing Rails running, port 80 open, and the contents of the docker-compose.yml:
[loomio_logs_docker-compose.txt](https://github.com/loomio/loomio-deploy/files/13628368/loomio_logs_docker-compose.txt)

Contents of .env file:
[loomio_env.txt](https://github.com/loomio/loomio-deploy/files/13628409/loomio_env.txt)

Hoping you can help, I have Loomio running fine in another aws account, but creating new grey hairs trying to get it to run in this new account we have to use, thanks in advance....

**Comment by robguthrie** [comment]
oh wow. That just sounds horrible. sorry you have to deal with it.

I don't really want to work on that problem (for free) though, it's clearly not a problem with Loomio, it's AWS, docker, docker-compose etc.

If you want pro support I'm happy to help - you can buy a block of hours of my time, get in touch via rob@loomio.org if you like.

**Comment by kawigreen14r** [comment]
For those who might have the same problem, I was able to get the server to respond.  The answer was a simple goof on my part.  In the docker-compose.yml file, I didn't change the original ports command from EXPOSE to simply PORTS in the app definition.  Converted expose to ports, and viola, the app came up.

`
services:
  app:
    container_name: loomio-app
    image: ${LOOMIO_CONTAINER_IMAGE}:${LOOMIO_CONTAINER_TAG}
    restart: unless-stopped
    expose:
      - 80:3000
    env_file: ./.env
    environment:
      - VIRTUAL_HOST=${CANONICAL_HOST}
      - DATABASE_URL=postgresql://postgres:password@db/loomio_production
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./uploads:/loomio/public/system
      - ./storage:/loomio/storage
      - ./files:/loomio/public/files
      - ./plugins:/loomio/plugins/docker
      - ./import:/import
      - ./tmp:/loomio/tmp
    depends_on:
      - db
      - redis
`

**Comment by robguthrie** [comment]
Glad you sorted it out. Nice work.
