### ISSUE TITLE
Group Data Import Progress [Stalled?]

### ISSUE THREAD

**Issue by darrengoldner** [loomio/loomio-deploy#104]
I'm attempting to do a data import from a loomio.org group export and the import has been running for well over an hour. Is there any way to check the progress of the import?

This is effectively the command I'm running with a tmp folder
`GroupExportService.import('/import/your-group-data.json')`

Following the instructions [here](https://help.loomio.com/en/user_manual/groups/data_export/#import-your-group-data-on-another-Loomio-server)

**Comment by robguthrie** [comment]
@darrengoldner how did it go?

**Comment by darrengoldner** [comment]
Thanks @robguthrie. It went well! And we're up and running now so far without any issues noticed.

**Comment by robguthrie** [comment]
Amazing! Honestly, I'm a little surprised - but that's great news.
