### ISSUE TITLE
Migration error when deploying for first time

### ISSUE THREAD

**Issue by reesericci** [loomio/loomio-deploy#111]
![image](https://github.com/user-attachments/assets/2fcc841d-d613-4937-bdbf-3de9c094e9d7)

Brand new install from docker-compose

**Comment by robguthrie** [comment]
What command did you run?

**Comment by reesericci** [comment]
`docker compose up -d` then `docker compose logs app -f | tail`

**Comment by robguthrie** [comment]
something is odd. those migrations are from a long time ago. If you are starting a fresh install, there should be no database, and it will apply the schema.db file - ie: those migrations should never run on a new install.

So I recommend you delete the database volume and start again

**Comment by reesericci** [comment]
Alrighty - got it working by running `db:reset` and then `db:migrate`!
