### ISSUE TITLE
Mailin and SMTP issues

### ISSUE THREAD

**Issue by kadallah** [loomio/loomio-deploy#112]
Hello, big fan of Loomio here. We've been trying to deploy an instance on our own server for my collective for the last few months, but are stuck on getting the SMTP/Mailin piece working, and because this is necessary to register and log in to the server, we're at an impasse. 

I recently went through and configured Mailjet as our SMTP server, but we're still having issues. This is what our logs show after clicking continue with email:

`
loomio-app          | I, [2024-12-18T16:50:08.002781 #27]  INFO -- : source=rack-timeout id=6b22daf2-5114-44dd-ae33-448be2ef2376 timeout=15000ms state=ready
loomio-app          | I, [2024-12-18T16:50:08.134210 #27]  INFO -- : [6b22daf2-5114-44dd-ae33-448be2ef2376] method=GET path=/api/v1/profile/email_status format=json controller=API::V1::ProfileController action=email_status status=200 allocations=6995 duration=93.91 view=2.35 db=3.08
loomio-app          | I, [2024-12-18T16:50:08.136646 #27]  INFO -- : source=rack-timeout id=6b22daf2-5114-44dd-ae33-448be2ef2376 timeout=15000ms service=134ms state=completed
nginx-proxy-1       | nginx.1     | loomio.anansi.site 148.75.211.110 - - [18/Dec/2024:16:50:08 +0000] "GET /api/v1/profile/email_status?email=myemail%40gmail.com HTTP/2.0" 200 307 "https://loomio.anansi.site/dashboard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "172.18.0.8:3000"
nginx-proxy-acme-1  | 2024/12/18 16:50:10 Debounce minTimer fired
nginx-proxy-acme-1  | 2024/12/18 16:50:10 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
loomio-app          | I, [2024-12-18T16:50:15.919314 #27]  INFO -- : source=rack-timeout id=0d2403df-0c16-4c26-9dce-2bcc274e123b timeout=15000ms state=ready
loomio-redis        | 1:M 18 Dec 2024 16:50:17.090 * 100 changes in 300 seconds. Saving...
loomio-redis        | 1:M 18 Dec 2024 16:50:17.090 * Background saving started by pid 316
loomio-redis        | 316:C 18 Dec 2024 16:50:17.167 * DB saved on disk
loomio-redis        | 316:C 18 Dec 2024 16:50:17.170 * RDB: 0 MB of memory used by copy-on-write
loomio-redis        | 1:M 18 Dec 2024 16:50:17.191 * Background saving terminated with success
loomio-app          | I, [2024-12-18T16:50:21.447305 #27]  INFO -- : [0d2403df-0c16-4c26-9dce-2bcc274e123b] Delivered mail 6762fd486b247_1b1ab5839893@03f09d7a071e.mail (5010.2ms)
loomio-app          | I, [2024-12-18T16:50:21.448509 #27]  INFO -- : [0d2403df-0c16-4c26-9dce-2bcc274e123b] method=POST path=/api/v1/registrations format=json controller=API::V1::RegistrationsController action=create status=500 allocations=92233 duration=5522.20 view=0.00 db=19.81
loomio-app          | F, [2024-12-18T16:50:21.457753 #27] FATAL -- : [0d2403df-0c16-4c26-9dce-2bcc274e123b]   
loomio-app          | [0d2403df-0c16-4c26-9dce-2bcc274e123b] Net::OpenTimeout (execution expired):
loomio-app          | [0d2403df-0c16-4c26-9dce-2bcc274e123b]   
loomio-app          | [0d2403df-0c16-4c26-9dce-2bcc274e123b] app/services/login_token_service.rb:7:in `create'
loomio-app          | [0d2403df-0c16-4c26-9dce-2bcc274e123b] app/controllers/api/v1/registrations_controller.rb:16:in `create'
loomio-app          | [0d2403df-0c16-4c26-9dce-2bcc274e123b] app/helpers/locales_helper.rb:8:in `use_preferred_locale'
loomio-app          | [0d2403df-0c16-4c26-9dce-2bcc274e123b] app/helpers/locales_helper.rb:3:in `process_time_zone'
loomio-app          | I, [2024-12-18T16:50:21.458735 #27]  INFO -- : source=rack-timeout id=0d2403df-0c16-4c26-9dce-2bcc274e123b timeout=15000ms service=5539ms state=completed
nginx-proxy-1       | nginx.1     | loomio.anansi.site 148.75.211.110 - - [18/Dec/2024:16:50:21 +0000] "POST /api/v1/registrations HTTP/2.0" 500 46 "https://loomio.anansi.site/dashboard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "172.18.0.8:3000"
`

I believe this is where the issue lies:
`
loomio-app          | F, [2024-12-18T16:50:21.457753 #27] FATAL -- : [0d2403df-0c16-4c26-9dce-2bcc274e123b]   
loomio-app          | [0d2403df-0c16-4c26-9dce-2bcc274e123b] Net::OpenTimeout (execution expired):
loomio-app          | [0d2403df-0c16-4c26-9dce-2bcc274e123b]   
`

**Comment by robguthrie** [comment]
Just to help reduce the problem space here: I think you're saying that you're having trouble configuring outbound SMTP. I don't think mailin has anything to do with this.

There are a few closed issues from other people who had trouble configuring SMTP. Please read these and let me know how you get on:
https://github.com/loomio/loomio-deploy/issues?q=is%3Aissue+is%3Aclosed+smtp

**Comment by kadallah** [comment]
I have gone through most of those threads a few times, but haven't identified ways to address the issue through them, unfortunately. I'm open to revisiting them. 

On this most recent restart, I received this error that also leads me to believe this is a Mailin issue:
`
info: Webhook url: http://app:3000/email_processor/
loomio-mailin       | info: Log file: /var/log/mailin.log
loomio-mailin       | info: Spam score computation is disabled
loomio-mailin       | (node:15) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
loomio-mailin       | (Use `node --trace-warnings ...` to show where the warning was created)
loomio-mailin       | info: Mailin Smtp server listening on port 25
loomio-mailin       | warn: Webhook http://app:3000/email_processor/ seems invalid or down. You may want to double check the webhook url.
`

**Comment by kadallah** [comment]
This is my config file, by the way:
`
LOOMIO_CONTAINER_IMAGE=loomio/loomio
LOOMIO_CONTAINER_TAG=stable
MAILIN_CONTAINER_IMAGE=loomio/mailin-docker
MAILIN_CONTAINER_TAG=latest
POSTGRES_CONTAINER_TAG=15.3

# this is the hostname of your app eg: loomio.org
CANONICAL_HOST=loomio.anansi.site

# email address of admin of the server for LetsEncrypt
SUPPORT_EMAIL=redacted

# the human name of the app (Default Loomio)
SITE_NAME=loomio.anansi.site

# reply-to in email notifications
REPLY_HOSTNAME=redacted

# hostname of the node.js app that handles websocket stuff
CHANNELS_URL=wss://channels.loomio.anansi.site
HOCUSPOCUS_URL=wss://hocuspocus.loomio.anansi.site

# smtp settings
SMTP_AUTH=plain
SMTP_DOMAIN=mail.anansi.site
SMTP_SERVER=smtp.mailgun.org
SMTP_PORT=25
SMTP_USERNAME=redacted
SMTP_PASSWORD=redacted
SMTP_USE_SSL=1
`

**Comment by kadallah** [comment]
I was able to get it up and running :) I think it was a combo of:

- getting my DNS records verified
- setting port to 465 **and** turning on SSL (any other combination, including port 25 with SSL off did not work)
