### ISSUE TITLE
SKYLIGHT unable to start

### ISSUE THREAD

**Issue by jagmumid** [loomio/loomio-deploy#29]
I have deployed the loomio on a linux, started successfully but while checking the logs i have noticed the following error

[SKYLIGHT] [1.6.0] Unable to start, see the Skylight logs for more details
loomio_1       | Warning: method `update` already defined
db_1           | ERROR:  database "loomio_production" already exists
db_1           | STATEMENT:  CREATE DATABASE "loomio_production" ENCODING = 'utf8'
loomio_1       | [121] * Listening on tcp://0.0.0.0:3000
loomio_1       | [121] Use Ctrl-C to stop
loomio_1       | [121] - Worker 0 (pid: 

I cant find the skylight logs located, can you please help to resolve this issue.

**Comment by robguthrie** [comment]
You can safely ignore skylight messages. It's a gem that reports performance metrics but isn't used on the docker deploys.

**Comment by gdpelican** [comment]
We should remove skylight from the gemfile anyway, we don't check it even
on loomio.org
