### ISSUE TITLE
Angular asset missing

### ISSUE THREAD

**Issue by ybabel** [loomio/loomio-deploy#35]
When I installed loomio, it worked (mostly), but angular css and other scripts where missing.

1st issue during install was : 
`docker-compose run loomio rake db:setup`
is to be changed by : (loomio entry does not exist anymore in the docker-composer.yml)
`docker-compose run app rake db:setup`

2nd issue during display, to correct it I had to : 
```
docker exec -ti loomio-app /bin/bash
bundle exec rake plugins:install client:build
```

**Comment by robguthrie** [comment]
Hi @ybabel thanks for reporting these issues and providing suitable remedies!

I'll be revisiting the docker image soon and will update the readme as I go.

**Comment by Pindar** [comment]
@ybabel did you apply resource limits to your container? I had the same issue (https://github.com/loomio/loomio/pull/5024) and it seems that it was a memory limit issue. It would be nice to know if you can confirm that too.

**Comment by Pindar** [comment]
Unfortunately yes. I tried the master version (before I was working with stable) and emojis aren't generated. Grunt compile completed but somehow not all required assets are available.

**Comment by ybabel** [comment]
For met it's working now. I haven't cheked the emojis yet though ...

**Comment by Pindar** [comment]
Emojis are generated but aren't loaded:
`img/emojis/1f642.png` works, but `img/emojis/1f642.png?v=2.2.7` don't. Any idea why this happens?

**Comment by robguthrie** [comment]
Hi, I've fixed this issue now. Pull the latest stable docker image and you should find they're all there now.
