### ISSUE TITLE
upgrading the DB requires the container to be up

### ISSUE THREAD

**Issue by db0** [loomio/loomio-deploy#43]
In the readme guide, it says to down the containers, pull then upgrade. However in this order it gives an error

```
# docker exec -ti loomio-app rake db:migrate
Error: No such container: loomio-app
```
I put everything up again, run the command which upgraded correctly, then restarted everything and it worked.

**Comment by robguthrie** [comment]
Thanks for the tip. Yea, I noticed this the other day too. I'll update it to say stop,start rather than down, up.

**Comment by syamgk** [comment]
@robguthrie so while running `# docker exec -ti loomio-app rake db:migrate`[1] both the loomio-app and postgres container should be in running state,

 that means bring down the old `loomio-app` container and run the latest `loomio-app` image and running the migrate cmd is the way to go right?

**Comment by robguthrie** [comment]
Thanks. I've corrected this now.
