### ISSUE TITLE
Following docker-compose instructions gives 'FATAL:  database "loomio_production" does not exist'

### ISSUE THREAD

**Issue by mozboz** [loomio/loomio-deploy#44]
Followed install instructions exactly on machine with 8Gb RAM and docker already up and running, and get exactly the same issue as described here with several errors that start with 'ActiveRecord::NoDatabaseError: FATAL:  database "loomio_production" does not exist'

https://www.loomio.org/d/gKrpCZs3/installation-on-docker-database-loomio_production-does-not-exist

My full error message here: https://pastebin.com/apPVChS4

The remedy give by @robguthrie seemed to work, which is to first run:

`docker exec -ti loomio-db su - postgres -c 'createdb loomio_production'`

Then run

`docker-compose run app rake db:setup`

**Comment by robguthrie** [comment]
this is resolved now. thanks for reporting and sorry for the hassles
