### ISSUE TITLE
Run loomio with SSO (keycloak)

### ISSUE THREAD

**Issue by Kayoku** [loomio/loomio-deploy#47]
Hi,

I would like to run dockerized Loomio with some others services (as nextcloud / rocketchat) with different domain behind a nginx-proxy, with SSO (manage by keycloak).

Is it possible to configure a SSO configuration for loomio ? I don't find any information about this...
Thank you :)

**Comment by samuk** [comment]
Is OIDC SSO supported?

**Comment by samuk** [comment]
Found this https://www.loomio.com/d/CL8Xr5kW/is-sso-compatible-with-selfhosted-loomio-/15
