### ISSUE TITLE
Error starting userland proxy

### ISSUE THREAD

**Issue by CodeFreezr** [loomio/loomio-deploy#49]
Hello dear loomio Team,

probably I have only a simple config mismatch. But at the moment I can't figure out, where to dig deeper to solve the problem:

```
docker-compose up -d
Removing loomio-mailin
Starting loomio-db    ... done
Starting loomio-redis ... done
Starting loomio-app    ... done
Starting loomio-worker ... done
Starting loomio-nginx  ...
Starting d7f5041e4d10_loomio-mailin ... error

Starting loomio-nginx               ... error
ddd28dd7d5f52d2e687461e0b5154e09255330dc631): Error starting userland proxy: listen tcp 0.0.0.0:25: bind: address already in use'

ERROR: for loomio-nginx  Cannot start service nginx: b'Cannot link to a non running container: /b0e0319e8327_loomio-app AS /loomio-nginx/app'

ERROR: for mailin  Cannot start service mailin: b'driver failed programming external connectivity on endpoint d7f5041e4d10_loomio-mailin (c087a28ba90607a8dd622ddd28dd7d5f52d2e687461e0b5154e09255330dc631): Error starting userland proxy: listen tcp 0.0.0.0:25: bind: address already in use'

ERROR: for nginx  Cannot start service nginx: b'Cannot link to a non running container: /b0e0319e8327_loomio-app AS /loomio-nginx/app'
ERROR: Encountered errors while bringing up the project.
```
[loomio-compose.log](https://github.com/loomio/loomio-deploy/files/3453518/loomio-compose.log)

Any ideas?

1000thx-in-advance

**Comment by CodeFreezr** [comment]
After killing a preinstalled sendmail and a 

docker-compose up -d --force-recreate --build

Everything seems to be ok. But a damn

503 Service Temporarily Unavailable

loughs at me.

See last log attached.
[loomio2.log](https://github.com/loomio/loomio-deploy/files/3453628/loomio2.log)

**Comment by CodeFreezr** [comment]
I tried a docker-compose down and then docker-compose up -d

Now I can see http requests in my docker-compose logs But still 503 ...

**Comment by robguthrie** [comment]
Loomio expects it is on a public facing server with a domain name. Let's encrypt assumes this too.

Are you intending to run SSL on a public url?

**Comment by CodeFreezr** [comment]
Ah ok, it's not possible to run this in our intranet in a VPC?

**Comment by CodeFreezr** [comment]
Our Idea was that we install loomio inside our intranet with internal DNS-Naming. beside wekan, jenkins, gitlab, ...

Is that easy possible?

**Comment by robguthrie** [comment]
Yes it's not too hard, you need to remove nginx and letsencrypt from the docker-compose file.

Map port 80 to port 3000 on the ruby app and remove the FORCE_SSL option in the env file.

I've included an attempt to modify the docker-compose.yml file

```

app:
  container_name: loomio-app
  restart: always
  image: ${LOOMIO_CONTAINER_IMAGE}:${LOOMIO_CONTAINER_TAG}
  ports:
    - 80:3000
  env_file: ./env
  links:
    - db
    - redis
  environment:
    - DATABASE_URL=postgresql://postgres:password@db/loomio_production
    - REDIS_URL=redis://redis:6379
  volumes:
    - ./client:/loomio/public/client
    - ./uploads:/loomio/public/system
    - ./files:/loomio/public/files
    - ./plugins:/loomio/plugins/docker
    - ./import:/import

worker:
  container_name: loomio-worker
  restart: always
  image: ${LOOMIO_CONTAINER_IMAGE}:${LOOMIO_CONTAINER_TAG}
  env_file: ./env
  links:
    - db
  environment:
    - DATABASE_URL=postgresql://postgres:password@db/loomio_production
    - TASK=worker
  volumes:
    - ./client:/loomio/public/client
    - ./uploads:/loomio/public/system
    - ./files:/loomio/public/files
    - ./plugins:/loomio/plugins/docker

db:
  container_name: loomio-db
  restart: always
  image: postgres:${POSTGRES_CONTAINER_TAG}
  volumes:
    - ./pgdata:/pgdata
    - ./pgdumps:/pgdumps
  environment:
   - POSTGRES_PASSWORD=password
   - PGDATA=/pgdata

redis:
  container_name: loomio-redis
  restart: always
  image: redis:5.0

mailin:
  container_name: loomio-mailin
  restart: always
  image: ${MAILIN_CONTAINER_IMAGE}:${MAILIN_CONTAINER_TAG}
  ports:
    - "25:25"
  links:
    - app
  environment:
    - WEBHOOK_URL=http://app:3000/email_processor/
```

**Comment by CodeFreezr** [comment]
Nice! 1000++ thx for your support. One last thing. I've got this Log-Entry 
"loomio-app | Redirected to https://..."
In the end this would be fine, but for the moment I can't install the correct SSL-Stuff.
Where could I disable / enable this 301 redirection?

**Comment by CodeFreezr** [comment]
Ah, now I'm tricked. Our normal System Setup we work like this: 

User > HTTPS > Loaldbalancer > HTTP > loomio-url

We terminate SSL on the Loadbalancer. But then there is the 301 inside loomio redirect to HTTPS, this led to a nice merry-go-round.

**Comment by robguthrie** [comment]
Have you removed the force ssl config line?
I think seeing some logs might help me understand what's happening better.

**Comment by CodeFreezr** [comment]
Thanx for your patience, and your great support till now. After killing another Port:25 Service again, removing force ssl build stuff from scratch I could reach the server. So I close this issue.
