### ISSUE TITLE
Lost of uploaded files

### ISSUE THREAD

**Issue by FramaJosephK** [loomio/loomio-deploy#5]
In `docker-compose.yml`, the folder `attachments` is mounted in `public/system/attachments` but some others folders in `public/system` contains uploaded files like users and groups avatars.
These files are lost after a `docker-compose down`

I suggest to replace the line
`- ./attachments:/loomio/public/system/attachments`
by
`- ./uploads:/loomio/public/system/`

**Comment by modulistic** [comment]
I agree with this; I would send a pull request but I feel this belongs to Loomio itself, the name "system" for the uploads directory feels a bit confusing to me. However this will also require manual action when upgrading, and thus an item in the release notes. But it's been broken for a while now.

**Comment by robguthrie** [comment]
Sorry about this and thanks for the PR @modulistic
