### ISSUE TITLE
Can't see Groups

### ISSUE THREAD

**Issue by CodeFreezr** [loomio/loomio-deploy#51]
On our local vpc installation (1000 thanks to @robguthrie for your help), we can now add groups in the admin panel. We also see some users. But we can't see these groups in the normal dashboard.

See Group-Export: 
[MyTestGroup.json.txt](https://github.com/loomio/loomio-deploy/files/3530298/MyTestGroup.json.txt)

If you need more infos, we could create some logfile-exports.

**Comment by robguthrie** [comment]
Oh..  I get it. You're creating groups via /admin? I've never done that, and it's basically undefined behaviour.

I would suggest you start groups as a normal use from the the main app then invite people in.
