### ISSUE TITLE
Group's not accessible?

### ISSUE THREAD

**Issue by CodeFreezr** [loomio/loomio-deploy#54]
Hi @robguthrie,

I fear we closed the first Group-Issue a bit too fast, because it also doesn't work from the main dashboard page. Because of that I tried to create some groups on the admin page. 

Today I tried it again from the dashboard-page. After clicking on "Gruppe anlegen" nothing happend. But in the Admin-Panel I see the Group "testGroup-Open". See attache a log-excerpt.

[create-group-log.txt](https://github.com/loomio/loomio-deploy/files/3540748/create-group-log.txt)

**Comment by CodeFreezr** [comment]
Any Ideas, what I can analyse to find the root cause?

**Comment by robguthrie** [comment]
Hi (sorry for the delay) have you run `rake db:migrate` or the corresponding docker command?

It looks like you might have setup the db a while ago then pulled a new image more recently, is that possible?

**Comment by CodeFreezr** [comment]
YES! Now it seems to working. Let's say a new loomio-baby is born, now it's time to read the further user-manuals^^ 1000 Thanks for your help.

**Comment by CodeFreezr** [comment]
One last thing. During my tests I have created a lot of useless groups. How can I delete them the easiest way?

**Comment by robguthrie** [comment]
The groups admin panel has a delete spam batch operation. Checkboxes down the left hand side and action menu at the top.

**Comment by robguthrie** [comment]
That's wonderful news. Thanks for persevering - let me know how it goes.
