### ISSUE TITLE
Can't delete Groups

### ISSUE THREAD

**Issue by CodeFreezr** [loomio/loomio-deploy#55]
Hope this is only a short one.

Select some groups in Admin-Panel, select "Stapelverarbeitung" aka "Batchprocessing" press "Delete spam ausgewählte". This runs into a "We're sorry, but something went wrong." error-page.

See Logs for details.

[cant-delete-groups.txt](https://github.com/loomio/loomio-deploy/files/3559750/cant-delete-groups.txt)

**Comment by robguthrie** [comment]
This was an error with ActiveAdmin, has been fixed
