### ISSUE TITLE
Optional nginx configuration

### ISSUE THREAD

**Issue by thiras** [loomio/loomio-deploy#57]
Hello. Thanks for great project, docker and companion scripts. But our machine that we are planning to deploy loomio on has nginx already. It would be great if we have alternative for non-nginx version of the deployment script.

**Comment by robguthrie** [comment]
Thanks for saying so. We're unable to provide support for this (there is so much more involved than nginx), but If you end up writing something or hiring someone, please do share it back.

**Comment by robguthrie** [comment]
Just following up. I don't want to discourage you from running Loomio. But I'm not able to support custom configurations. I support 1 deployment system and do my very best with it, and make it as simple and complete as possible, then spend the rest of my time making Loomio better. I encourage you to just setup your system as I recommend if you can possibly manage the the time or cost - it's very expensive (in terms of time not working on Loomio features) for me to support you.

**Comment by thiras** [comment]
Hello. Thanks for replying fast. I totally understand your concerns. I'll try to deploy it without nginx. I'll let you know the procedure if I success. Than maybe we can a small how-to note about it to documentation with disclaimer warning.
