### ISSUE TITLE
Missing environments list

### ISSUE THREAD

**Issue by thiras** [loomio/loomio-deploy#58]
Hello.

I've tried to look both loomio and loomio-deploy repos to find full list of environments loomio app accepts.

Could you guide us about that? Even pure list of the environments (without explanation) is OK.

**Comment by garyritchie** [comment]
I think most of them are here: https://github.com/loomio/loomio-deploy/blob/master/scripts/default_env

**Comment by robguthrie** [comment]
Thanks for helping out, @garyritchie.

Also the env file (generated from default_env) is supposed to have everything you could want. It's the list you're looking for
