### ISSUE TITLE
Deprecated links annotation on compose file

### ISSUE THREAD

**Issue by thiras** [loomio/loomio-deploy#59]
Hello.

As you can see [here](https://docs.docker.com/compose/compose-file/#links) `links` notation is deprecated already. No need to create links between them since docker create a network between all containers by default.

Would you like to have a PR to fix it?

**Comment by robguthrie** [comment]
If you're sure things still work after this change, then yes please. I appreciate the support!

**Comment by thiras** [comment]
I'll take a test from scratch just to be sure nothing is broken after #62 merge.

**Comment by robguthrie** [comment]
thank you!
