### ISSUE TITLE
Instruction to connect to LDAP or Active Directory

### ISSUE THREAD

**Issue by damageco** [loomio/loomio-deploy#6]
Hello,

Please, can you provide instruction to connect Loomio to OpenLDAP or Active Directory ?

Thanks

David

**Comment by gdpelican** [comment]
Hey @damageco , this isn't something we have strong support for at the moment, but it is on our roadmap for early this year.

**Comment by uschreck** [comment]
Hello,

are there any updates when LDAP connection will be available? 
Thanks Uli

**Comment by robguthrie** [comment]
Sorry no. We've been adding new decision types and support for Facebook and Slack so far. Would be interested in talking with a company/organisation that is willing to pay to support the development of LDAP
