### ISSUE TITLE
Shorten install instructions with getting rid of unnecessary DB create command

### ISSUE THREAD

**Issue by thiras** [loomio/loomio-deploy#60]
Hello.

As you can see [here](https://hub.docker.com/_/postgres) under the Environment Variables, there is a `POSTGRES_DB` variable which creates a database on the first start of the container. So technically there is no need to run `docker exec -ti loomio-db su - postgres -c 'createdb loomio_production'` command as documentation suggest. It's enough to put `POSTGRES_DB` into env file or docker-compose's environment section of db.

I can send a quick PR to fix it if it's OK for you. Please let me know.

**Comment by robguthrie** [comment]
That's great! Please do. Thanks.
