### ISSUE TITLE
SSO available in self-hosted?

### ISSUE THREAD

**Issue by davidgut1982** [loomio/loomio-deploy#65]
I tried to configure the SSO, but it says "This feature is only available to Pro plan customers. Please check out our upgrade page for more details." if I click upgrade, it goes no where. 
Is there a way to setup SAML/OAUTH with Keyclock through the ENV file or something?
I've been able to setup SSO with Keycloak for a bunch of our other apps, like Wordpress, Doku-wiki, Nextcloud, and such. It would be nice to set this up for Loomio for our board members.

**Comment by robguthrie** [comment]
There are two kinds of SSO in loomio, a system wide, and a per group.

If you're self hosting use the system wide put the following into your env file:

SAML_APP_KEY=1
SAML_IDP_METADATA_URL=https://urlformetadata.com/metadata.xml
FEATURES_DISABLE_EMAIL_LOGIN=1

you can choose if you want to keep the disable email login or not.

**Comment by davidgut1982** [comment]
Why does the metadata have to be a file? Can I point it my root HTML/WWW of loomio? If so, how do I do that?
If I enable SSO, does that mean all users have to do SSO? I noticed that since I've enabled it, I cannot use the loomio database and it switches over primarily to the SSO.

**Comment by robguthrie** [comment]
Metadata is fetched from the authentication provider, it's always a HTTPS URL. This is all just directly using Ruby-SAML Gem.  Either we fetch metadata or you need to configure each setting manually, which I don't have any intention of supporting.

If you "disable email login" then you must authenticate via SAML. Take that line out and you can login via email or SAML
