### ISSUE TITLE
Loomio (self hosted) system wide SSO not working for me

### ISSUE THREAD

**Issue by dharmeshgordhan** [loomio/loomio-deploy#70]
Hi, 

I'm self-hosting Loomio on an ECS cluster. I'm looking to enable SSO with Azure Active Directory. I'm not using the nginx-proxy, and rather using an ALB (doing SSL termination at this ALB). 

When I set: `SAML_APP_KEY=1`, `SAML_ISSUE=id`, `SAML_IDP_METADATA_URL=url` in my `env` file,
And then I load the application in a browser
And then I click Sign in with SAML
And then I get directed to `https://login.microsoftonline.com/blah/saml/blahblah`
And then I get redirected back to my loomio instance.
And I'm presented with the login screen, and I don't appear to have a session :(
And then I successfully complete username/password login with loomio, 
But subsequent POST requests, example: to update my profile or create a new organisation throw a 403 :/

By chance, anyone seen this before? I'm wondering if the application needs some specific SAML attribute my AAD isn't providing. 

There's no errors in the logs I can see.
```
Started GET "/saml/oauth?back_to=https://server/dashboard" for ....
Parameters: {"back_to"=>"https://server..."}
Processing by Identities::SamlController#oauth as HTML
Redirected to https://login.microsoftonline.com/blahblah
Completed 302 Found in 861ms (ActiveRecord: 1.6ms)
Started POST "/saml/oauth" for ...
Parameters: {"SAMLResponse"=>"...SAML"}
Processing by Identities::SamlController#create as HTML
#<OneLogin::RubySaml::Response:0x000055f2ed503350>
Redirected to https://server/dashboard
Started GET "/dashboard" for ...
```

nb: There are errors related to cable / ws (`Failed to upgrade to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: upgrade, HTTP_UPGRADE: websocket`) but I _think_ that's unrelated.

**Comment by robguthrie** [comment]
Yes, those WS errors are unrelated.

Do normal, email auth sessions work for you?

Are you able to see anything from the SAML provider end of things?

We might have to insert some debug info into the saml controller to debug this.

We have no previous experience integrating with microsoftonline, so can't say it's worked before, and it might need something special, no idea.

**Comment by dharmeshgordhan** [comment]
>Do normal, email auth sessions work for you?

When I disable SAML/SSO in my env file - email auth sessions works fine.

> Are you able to see anything from the SAML provider end of things?

On the SAML Provider side - we can see successful logins in the IDP logs. 

> We have no previous experience integrating with microsoftonline, so can't say it's worked before, and it might need something special, no idea.

Microsoft Online is the same as Microsoft Azure Active Directory? Which I believe works for single org SAML from the docs?

**Comment by robguthrie** [comment]
Actually, yes, we have integrated it in the past, I forgot, because that customer is no longer active.

Looks like we'll need to debug the responses to work out what to do next here.

Sorry I don't have time to pour into this today.. The key file is app/controllers/identities/saml_controller.rb

**Comment by dharmeshgordhan** [comment]
No worries at all. I'll look to add some debug commands to that file. Thanks for the guidance :)

**Comment by dharmeshgordhan** [comment]
I've been playing around...

NB: I've got `FORCE_SSL=1`.

When I set `CANONICAL_HOST=example.com` SSO doesn't work as the `assertion_consumer_service_url` (the reply url) and `issuer` comes through as `http://example.com/saml/...` whereas I need them to be https. 

When I set `CANONICAL_HOST=https://example.com` SSO now works as the `assertion_consumer_service_url` and `issuer` use https in the urls, but sessions break, and I also cannot sign in via emails. I _think_ this is because the cookies are not getting set, which is because the cookie's domain gets set to `domain=https://example.com" (vs `domain=example.com`).

I can go back to setting `CANONICAL_HOST=example.com` as I can set the `SAML_ISSUER=https://example.com/saml/metadata`, but I'm not too sure how to then set `assertion_consumer_service_url`.

Any ideas?

**Comment by robguthrie** [comment]
You cannot put the scheme into the CANONICAL_HOST it will not work. It is for domain part only. Don't even try.

(I've only used amazon stuff once a few years ago, best to assume I don't know it)

So, to be clear, you have a HTTPS frontend feeding HTTP requests to the Rails app eh? I think that's the root of the problem.

Rails detects HTTPS usage (and hostname, etc actually) per request and builds ..._url routes based on that per request config.

I don't know what the right way to do what you want to do, is. But the answer is Rails rather than Loomio specific, and must have been solved plenty of times already.

From what I can see you need to keep things HTTPS all the way, or provide some specific header information in during the request passing.

https://stackoverflow.com/questions/14498315/set-secure-flag-on-session-cookie-in-ror-even-over-http

**Comment by dharmeshgordhan** [comment]
nb: This is my first time looking at rails.

Yeah - i'm doing SSL termination at the ALB (at least right now I am), and I'm sending http requests to the container. This is the same as what nginx-proxy is doing in the docker-compose step tho right?

Anyways, I'll set CANONICAL_HOST without a scheme - that's not a problem. The only bit now, is the SAML `assertion_consumer_service_url` is sent through as http, not https. 

I'm not too sure how `saml_oauth_callback_url` gets set. 
https://github.com/loomio/loomio/blob/master/app/controllers/identities/saml_controller.rb#L35

**Comment by robguthrie** [comment]
Sorry I've not gotten back to you. This is just way outside of my area of experience and I don't know how to do what you're attempting. Sorry and Good luck!

I'll leave this issue open for a few weeks to see if it helps you with finding a collaborator, otherwise I'll close it.

**Comment by robguthrie** [comment]
Finally, unrelated, but I've just done some work to remove the Websocket errors you mentioned.
