### ISSUE TITLE
error

### ISSUE THREAD

**Issue by fokenhelpmy** [loomio/loomio-deploy#71]
Hi Guys

I seem to run into this error now, and the site will not work
so i figured to run this command as it seems to be a db issue docker-compose run app rake db:migrate 

Starting loomio-db ... done
Starting loomio-redis ... done
** Invoke db:migrate (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
PG::ConnectionBad: could not connect to server: Connection refused
        Is the server running on host "db" (172.17.0.2) and accepting
        TCP/IP connections on port 5432?

Im at a loss, and not sure wht to do to fix it
thanks

**Comment by robguthrie** [comment]
Hi, (I believe) this is a bug with the latest postgres image and the older docker-compose.yml format we used to use. Try git pull or update your docker-compose.yml to match master.

**Comment by fokenhelpmy** [comment]
thanks. 
i did the pull and it didnt work.
i will try the master docker compose.yml

**Comment by fokenhelpmy** [comment]
so after adding the docker-compose.yml it worked to some extend.
now this happens
this used to be a fully working site.

loomio-nginx   | nginx.1    | 2020/07/15 21:57:17 [error] 151#151: *43 connect() failed (111: Connection refused) while connecting to upstream, client: 102.32.37.72, server: talk.joziburners.org.za, request: "GET / HTTP/2.0", upstream: "http://172.18.0.6:3000/", host: "talk.joziburners.org.za"
loomio-nginx   | nginx.1    | 2020/07/15 21:57:17 [error] 151#151: *43 connect() failed (111: Connection refused) while connecting to upstream, client: 102.32.37.72, server: talk.joziburners.org.za, request: "GET / HTTP/2.0", upstream: "http://172.18.0.8:3000/", host: "talk.joziburners.org.za"

**Comment by fokenhelpmy** [comment]
just starting working out of its own again
Thanks for the help.

**Comment by robguthrie** [comment]
Great!
