### ISSUE TITLE
Links in emails being sent as http not https when FORCE_SSL=1

### ISSUE THREAD

**Issue by dharmeshgordhan** [loomio/loomio-deploy#72]
Hey, pretty much the title. Not too sure why this might be happening. The image links are https. Just not the text links. Weirdly, it doesn't happen in another docker stack I setup with almost identical settings - any ideas, or suggestions on where to look to debug this?

**Comment by robguthrie** [comment]
Sorry, no idea.

https://github.com/loomio/loomio/blob/master/config/application.rb#L127

Shows that HTTPS is selected by FORCE_SSL... so I would say it's either your worker or app image needs to be properly rebuilt or restarted.
