### ISSUE TITLE
Custom color palettes not working

### ISSUE THREAD

**Issue by chartgerink** [loomio/loomio-deploy#73]
Hi 👋 

Having lots of fun with Loomio, thanks for this great piece of software! I am running in to one issue regarding custom color palettes. 

More specifically, on a new instance, if I uncomment the custom palette colors in the `env` file, the instance still defaults to the Loomio base colors. 

```
THEME_PRIMARY_PALETTE=custom_primary
THEME_ACCENT_PALETTE=custom_accent
THEME_PRIMARY_PALETTE_CONFIG={"default": "500"}
THEME_ACCENT_PALETTE_CONFIG={"default": "500", "hue-1": "400", "hue-2": "300", "hue-3": "200"}
THEME_CUSTOM_PRIMARY_PALETTE={ "50": "f2e0e5", "100": "deb3bf", "200": "c98094", "300": "b34d69", "400": "a22648", "500": "920028", "600": "8a0024", "700": "7f001e", "800": "750018", "900": "63000f", "A100": "ff939b", "A200": "ff606c", "A400": "ff2d3c", "A700": "ff1425", "contrastDefaultColor": "light", "contrastDarkColors": [ "50", "100", "200", "A100", "A200" ], "contrastLightColors": [ "300", "400", "500", "600", "700", "800", "900", "A400", "A700" ] }
THEME_CUSTOM_ACCENT_PALETTE={ "50": "e9f4fb", "100": "c8e4f6", "200": "a3d3f0", "300": "7ec1ea", "400": "62b3e6", "500": "46a6e1", "600": "3f9edd", "700": "3795d9", "800": "2f8bd5", "900": "207bcd", "A100": "ffffff", "A200": "d2e8ff", "A400": "9fcfff", "A700": "85c2ff", "contrastDefaultColor": "light", "contrastDarkColors": [ "50", "100", "200", "300", "400", "500", "600", "700", "A100", "A200", "A400", "A700" ], "contrastLightColors": [ "800", "900" ] }
```

I tried finding some additional documentation but could not find any about these environment options. I did get the colors in the emails to configure properly, so it is confusing to me why this option doesn't work. I did not get any errors in the logs.

Any comments appreciated :)

**Comment by robguthrie** [comment]
Hi, yep looks like those are config variables for the old Loomio 1 interface, and the email templates.
There are other config vars for configuring the new Vuetify based interface.
I'll come back to this soon, but flooded right now, but some point over the next few days I'll update the config with working examples.

**Comment by chartgerink** [comment]
Thanks @robguthrie! Hope you get through your work in a healthy manner 🤗
