### ISSUE TITLE
Internal server error when trying to deploy Loomio

### ISSUE THREAD

**Issue by JeffLeFoll** [loomio/loomio-deploy#74]
Hello,

I'm trying to deploy Loomio on an Ubuntu 18 server.  
I follow the instructions from the ReadMe, but I go to https//my.loomio.instance I ran into an Internal Server Error.  

When looking into the log I see the following error :  

`
loomio-app     | app/controllers/application_controller.rb:71:in `read'
loomio-app     | app/controllers/application_controller.rb:71:in `boot_app'
loomio-app     | app/controllers/application_controller.rb:30:in `index'
loomio-app     | app/helpers/locales_helper.rb:8:in `use_preferred_locale'
loomio-app     | app/helpers/locales_helper.rb:3:in `process_time_zone'
loomio-app     | source=rack-timeout id=aba4e148-a4b3-45e6-bb1e-3f1c7fd3d964 timeout=15000ms service=25ms state=completed
loomio-app     | source=rack-timeout id=de4a03d1-ad27-4cd0-99e5-335e84644fa3 timeout=15000ms state=ready
loomio-app     | Started GET "/dashboard" for 90.27.243.84 at 2020-08-12 15:35:17 +0000
loomio-app     | Processing by ApplicationController#index as HTML
loomio-app     | Completed 500 Internal Server Error in 11ms (ActiveRecord: 0.0ms)
loomio-app     |
loomio-app     | Errno::ENOENT (No such file or directory @ rb_sysopen - /loomio/public/client/vue/index.html):
`

Do you have an idea of what I'm doing wrong ?

Thank you very much.

**Comment by chartgerink** [comment]
Could you post what you're actually doing? It seems like it's waiting for the full deploy to finish and the app isn't fully set up. It can take a while after you run `docker-compose up -d` (especially first time). It took my instance around 30min.

**Comment by JeffLeFoll** [comment]
ok, so I wait until now and I have the same issue.  

What I did :  
I've started with a fresh instal of ubuntu (2 GB of RAM), then Ive followed the readme : 
- Installed docker & docker compose 
- Created the ENV files
- docker-compose up -d db
- docker-compose run app rake db:setup
- docker-compose up -d

As of now the complete log I have is :  
```
loomio-nginx   | nginx.1    | yy.yy.yy.yy ww.ww.ww.ww - - [13/Aug/2020:14:54:32 +0000] "GET /.git/config HTTP/1.1" 503 197 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/70.0"  
loomio-app     | source=rack-timeout id=693ea53c-c23a-448f-9c7d-7a1eb8595531 timeout=15000ms state=ready  
loomio-app     | Started GET "/" for xx.xx.xx.xx at 2020-08-13 14:55:48 +0000  
loomio-app     | Processing by RootController#index as HTML  
loomio-app     | Redirected to https://my.loomio.instance/dashboard  
loomio-app     | Completed 302 Found in 308ms (ActiveRecord: 7.0ms)  
loomio-app     | source=rack-timeout id=693ea53c-c23a-448f-9c7d-7a1eb8595531 timeout=15000ms service=318ms state=completed  
loomio-nginx   | nginx.1    | my.loomio.instance xx.xx.xx.xx - - [13/Aug/2020:14:55:49 +0000] "GET / HTTP/2.0" 302 117  "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0"  
loomio-app     | source=rack-timeout id=b369bd65-8d8c-4b04-862b-b55370f4f49b timeout=15000ms state=ready  
loomio-app     | Started GET "/dashboard" for xx.xx.xx.xx at 2020-08-13 14:55:49 +0000  
loomio-app     | Processing by ApplicationController#index as HTML  
loomio-app     | Completed 500 Internal Server Error in 29ms (ActiveRecord: 0.0ms)  
loomio-app     |  
loomio-app     | Errno::ENOENT (No such file or directory @ rb_sysopen - /loomio/public/client/vue/index.html):  
loomio-app     |  
loomio-app     | app/controllers/application_controller.rb:71:in `read'   
loomio-app     | app/controllers/application_controller.rb:71:in `boot_app'  
loomio-app     | app/controllers/application_controller.rb:30:in `index'  
loomio-app     | app/helpers/locales_helper.rb:8:in `use_preferred_locale'  
loomio-app     | app/helpers/locales_helper.rb:3:in `process_time_zone'  
loomio-app     | source=rack-timeout id=b369bd65-8d8c-4b04-862b-b55370f4f49b timeout=15000ms service=47ms state=completed  
loomio-nginx   | nginx.1    | my.loomio.instance xx.xx.xx.xx - - [13/Aug/2020:14:55:49 +0000] "GET /dashboard HTTP/2.0" 500 672 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0"  
loomio-nginx   | nginx.1    | 2020/08/13 14:55:49 [error] 85#85: *44 connect() failed (111: Connection refused) while connecting to upstream, client: xx.xx.xx.xx, server: my.loomio.instance, request: "GET /theme/icon.png HTTP/2.0", upstream: "http://zz.zz.zz.zz/theme/icon.png", host: "my.loomio.instance"  
loomio-nginx   | nginx.1    | my.loomio.instance xx.xx.xx.xx - - [13/Aug/2020:14:55:49 +0000] "GET /theme/icon.png HTTP/2.0" 499 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0"  
loomio-nginx   | nginx.1    | my.loomio.instance xx.xx.xx.xx - - [13/Aug/2020:14:55:49 +0000] "GET /fonts/roboto-v18-latin-regular.woff2 HTTP/2.0" 499 0 "https://my.loomio.instance/assets/basic/all.self-d9f07265a2b5a69ebe28257d4d2664c8c0772a93bf78317505cbd1f6b9362543.css?body=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0"  
loomio-app     | source=rack-timeout id=7b9a1950-e6b0-4eb2-b587-d06e13d6af96 timeout=15000ms state=ready  
loomio-app     | source=rack-timeout id=7b9a1950-e6b0-4eb2-b587-d06e13d6af96 timeout=15000ms service=21ms state=completed  
loomio-app     | [ActiveJob] [Ahoy::GeocodeV2Job] [af6c17df-662c-4127-ace4-830db4d69e82] Performing Ahoy::GeocodeV2Job (Job ID: af6c17df-662c-4127-ace4-830db4d69e82) from Async(ahoy) with arguments: "32af709a-9e0f-46a4-8a63-b72cf9286368", "90.27.243.0"  
loomio-nginx   | nginx.1    | my.loomio.instance xx.xx.xx.xx - - [13/Aug/2020:14:55:49 +0000] "POST /ahoy/visits HTTP/2.0" 200 128 "https://my.loomio.instance/dashboard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0"  
loomio-app     | [ActiveJob] [Ahoy::GeocodeV2Job] [af6c17df-662c-4127-ace4-830db4d69e82] Performed Ahoy::GeocodeV2Job (Job ID: af6c17df-662c-4127-ace4-830db4d69e82) from Async(ahoy) in 17.19ms  
```

**Comment by chartgerink** [comment]
Thanks @JeffLeFoll for the additional information :) 

Hm I don't know what's missing then. The `docker-compose up -d` command should create the `/loomio/public/client/vue` directories, and usually that missing means it's not done yet. 

How about you remove the `/loomio-deploy` folder and start from scratch? Something could've gone wrong in the setup.

**Comment by robguthrie** [comment]
Sorry I've been slow on this. I'll look into it now. Seems like the Vue app is not being compiled

**Comment by robguthrie** [comment]
Hi @JeffLeFoll.

edit docket-compose.yml and remove the line:

````
   - ./client:/loomio/public/client
````

under volumes in app. Or just `git pull origin master` from within loomio-deploy.

Sorry about this. I was sure I'd already taken that line out, but I was wrong. It's effectively overwriting the client with an empty directory.

Back story, Loomio used to have to build it's AngularJS based client on first boot (which is what contributed to the long booting time), because we had to compute theme/server specific details on build. 

Now the angular client is replaced by the Vue based client, we build the client when we build the docker image. So the app should start much more quickly.

**Comment by JeffLeFoll** [comment]
Thank you very much  @robguthrie , it works !
