### ISSUE TITLE
Semi broken UI after upgrade

### ISSUE THREAD

**Issue by EliotBerriot** [loomio/loomio-deploy#75]
I updated our loomio dockerized instance two days ago, and it resulted in a broken UI. In particular, icons are not loading (the icon font at URL `/fonts/mdi/materialdesignicons-webfont.woff2` returns a 404 apparently), and user avatars are not shown anymore.

You can view the result live at https://governance.funkwhale.audio/d/Iwoht0Xc/organizing-our-general-assembly, but I've include a screenshot below:

![image](https://user-images.githubusercontent.com/1970915/90959191-b66dcd80-e499-11ea-985d-073be5e34629.png)

I'm not sure how to fix it. This is the output of `sudo docker images loomio/loomio:latest`:

```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
loomio/loomio       latest              6643a435efa5        2 days ago          2.08GB
```

Let me know if you need additional info, and thank you in advance for the help.

**Comment by robguthrie** [comment]
Hi Eliot,

Sorry about this, 
Edit docker-compose.yml and take out the line under volumes:

```
- ./client:/loomio/public/client
```

**Comment by EliotBerriot** [comment]
It solved the issue, thank you @robguthrie!
