### ISSUE TITLE
no verification mail

### ISSUE THREAD

**Issue by MLG360Sepy** [loomio/loomio-deploy#78]
Hello

I 've set up loomio on an AWS instance. 
I changed the env SMTP files. And loomio seems to start when I enter loomio._domain_.com.
And immediately after I went to the website I get a pop-up screen for signing up. I enter my email,  choose a name. And i get the message that the email with verification code/link is sent to my e-mail address. 
But i never got a mail. Nor in my primairy inbox, nor my spamfolder.

- The SMTP files email is loomio@_domain_.com. 
- My domain has an MX-record:
hostname= loomio._domain_.com.
Mail provider's mail server= loomio._domain_.com.
TTL: 600
priority 0
- A-record;
loomio._domain_.com. to IP-AWS-instance TTL 600
- CNAME
Hostname=channels.loomio._domain_.com
Is an alias of= loomio._domain_.com
TTL 600

I use one.com for my domain settings.

What did I do wrong?
I'm new to setting up things, so no idea if you need anything more. Just ask and say what you'll need and where I can find it.
Thanks in avance.

**Comment by robguthrie** [comment]
Hi @MLG360Sepy 
Sorry your message was not answered earlier, during that time I was not on my computer for a couple of weeks.

You're going to want to tell me if you're using the standard docker-compose.yml setup, which includese the backgound job stuff, and then send me logs from immediately after requesting a login email.

**Comment by AliAyub007** [comment]
Facing same issue. Here are the logs 

[logs.txt](https://github.com/loomio/loomio-deploy/files/5937327/logs.txt)

**Comment by AliAyub007** [comment]
How and where to add custom SMTP server settings. I can't see that.

**Comment by chartgerink** [comment]
Hi @AliAyub007 --- looks like your `env` file is not successfully set up. Did you verify your mail provider is receiving the email for delivery? Your logs seem to show that your connection is failing (`SocketError`) which suggests your settings may be the problem. 

What mail provider are you using? I personally use Mailgun on our instance and have some experience debugging that 😉
