### ISSUE TITLE
env vars for notification settings

### ISSUE THREAD

**Issue by Apfelwurm** [loomio/loomio-deploy#80]
Hi togehter, im a new user of loomio and setted up my instance successfully. You have build a really nice peace of software here!
I have noticed there is an env var EMAIL_ON_PARTICIPATION_DEFAULT_FALSE=1 which works perfectly.
Now i have wondered if there are vars for disabling the default summary mail, the mentions & replies mail and the notifications for all groups?

I tried to understand where the EMAIL_ON_PARTICIPATION_DEFAULT_FALSE var is implemented in the loomia code but i was not able to find it, maybe also because i'm not very familiar with ruby.

Can someone tell me if there are already vars for that purpose or push me in the right direction where the logic is implemented so i eventually can build them and make a pr in the future? 

Thanks a lot!

**Comment by robguthrie** [comment]
Hi, @Apfelwurm, sorry to leave you hanging for a while.

You're on the right track.

If you follow that ENV through the code, it will tell you a lot about what you need to do to change enable setting the defaults on a new user with those from ENV.

In the future I intend to make it a group level setting, but for now, you approach is good. Let me know if you want more help.

**Comment by Apfelwurm** [comment]
Hi @robguthrie, thanks for your answer , no problem :)

I tried to follow the env (using recursive search with grep and in vscode) but i only can find it within the default env file here and nowhere in the loomio code itself or in scripts from your docker image.
So if you could point me to where it gets handled im sure i can get to understand how i can implement it but I'm currently not able to locate it :(

A group level setting would also be cool in the future!
