### ISSUE TITLE
"Connection refused"  "failed to load command puma" after update

### ISSUE THREAD

**Issue by Kaor** [loomio/loomio-deploy#83]
impossible to restart loomio after upgrade : 

```
docker-compose logs -f 

loomio-app | bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
No such file or directory @ rb_sysopen - tmp/pids/server.pid (Errno::ENOENT)
```

i create missing directories on container loomio-app : 

`docker exec xxx mkdir tmp/pids -p`

and it's ok !

**Comment by Kaor** [comment]
mmm on loomio-worker too ?

**Comment by robguthrie** [comment]
Thanks for letting me know, I'll upgrade some of our docker based systems
today, and let you know if I find the problem

**Comment by aiac** [comment]
> 
> 
> impossible to restart loomio after upgrade :
> 
> ```
> docker-compose logs -f 
> 
> loomio-app | bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
> No such file or directory @ rb_sysopen - tmp/pids/server.pid (Errno::ENOENT)
> ```
> 
> i create missing directories on container loomio-app :
> 
> `docker exec xxx mkdir tmp/pids -p`
> 
> and it's ok !

Thank you, same problem. Making tmp/pids directory solve it

**Comment by robguthrie** [comment]
Thanks for raising this issue. I've added a line to the docker_start.sh script to create this directory if it does not exist.
