### ISSUE TITLE
Custom OAuth Provider

### ISSUE THREAD

**Issue by dariusk** [loomio/loomio-deploy#88]
(Thanks for your help earlier today.)

My organization provides OAuth for a few different services and we'd like to use it for Loomio, too. I see that you support Facebook, Twitter, Google, and Slack from within the `.env` file, but I'd like to use a different OAuth service tied to a `login.example.com` that we host.

For most apps that don't support custom OAuth I use [Vouch](https://github.com/vouch/vouch-proxy), which acts as a wrapper to the app but also requires that I'm able to edit the nginx config on the server that the application is hosted. I could edit files directly in the `nginx-proxy` docker container but that seems a little brittle and not best practice, right?

How do self-hosting orgs that use their own OAuth manage this?

**Comment by dariusk** [comment]
I'm also happy to run Loomio on its own in production but _not_ with `loomio-deploy`, but that seems to be not recommended, as well.

**Comment by robguthrie** [comment]
Hi, it should be possible to get loomio to support a custom oauth, but I'm not sure how right now. If you need we could look into adding this as some sponsored development.

We do support SAML really well though, if that's possible with your setup?

You can edit the nginx.conf file within the loomio-deploy directory you have. It's currently just one line.

**Comment by robguthrie** [comment]
Custom OAUTH is added and documented now
